* Community Organizing Process in North America
** Discovering Care
What do the people in need care about fixing? The rich should not come in and just tell the poor how to improve. Find out what the poor are motivated to help improve.
*** Community Learning conversations
Community organizer has hour long conversations with different groups and individuals that represent the leadership in the community to identify what the community cares about. Use these conversations to also identify other people to have conversations with.
*** Form a connector-leaders group
Community leaders should have following qualities:
- ability to influence the community's associations and institutions
- care enough to act to help solve one or more of the top issues identified by the community
- willing to work with others rather than hold on to their little piece of power
*** connector leaders consider having more learning conversations
Have the community leaders continue to identify people and groups to talk with until there is a critical mass of people willing to act on the first major issue to be resolved (school dropouts, drugs, lenders, etc)
** Take Meaningful Action
*** Connector leader group chooses the top priority issue
Choose the issue. Encourage the group to pursue a strategy that incorporates:
- high chance of early and recognizable success
- can mobilize and connect people and groups in community more deeply than before
- can forge new connections with assets external to the community
*** Connector leader group forms community partnership to address the priority issue
Invite people from the community to join the community partnership. Make sure to include materially poor who are affected by the issue.
*** Community partnership researches a potential strategy to address the priority issue
Find out what has worked in other communities, gather training materials, talk to experts
*** Community partnership conducts a targeted asset mapping of the community
Don't take too long, just find out what resources already exist in the community who could help solve the problem.
*** Community partnership launches a project
Put a plan into action. Maybe it's financial stewardship courses or habitat for humanity style housing projects. Christian organizations can work alongside secular but include the gospel in their own implementation of the plan. This way they're still operating the same way they would have alone, but they have strengthened ties to other organizations in the community and started a wider movement.
*** Community partnership evaluates and celebrates
Come together to discuss how it went. Include the materially poor who were involved in the project. Celebrate any successes.
